set nocompatible              " be iMproved, required
filetype off                  " required

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin('~/.vim/bundle')
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/vim-auto-save'
Plugin 'airblade/vim-gitgutter'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'tpope/vim-surround'
Plugin 'mattn/emmet-vim'
Plugin 'othree/html5.vim'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'rust-lang/rust.vim'
Plugin 'elzr/vim-json'
Plugin 'stephpy/vim-yaml'
call vundle#end()
filetype plugin indent on

set number
syntax on

" Display the status line *always*
set laststatus=2
let g:solarized_termcolors=256
let g:auto_save_in_insert_mode = 0  " do not save while in insert mode

" Display the cursor line
set cursorline
hi CursorLine ctermbg=255 cterm=None gui=None
hi CursorLineNr ctermbg=255 cterm=None gui=None

" Display the color column
set colorcolumn=80

" Display a warning if &paste is set
set statusline+=%#error#
set statusline+=%{&paste?'[paste]':''}
set statusline+=%*

set statusline+=\ %t%m%r%h%w\ %=%({%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\&bomb)?\",B\":\"\")}%k\|%{&filetype}}%)\ %([%l,%v][%p%%]\ %)

set nofoldenable
" Enable JS syntax highliting
au FileType javascript call JavaScriptFold()

" Set the colorscheme
colorscheme grb256

nnoremap ; :
nnoremap : ;

let g:used_javascript_libs = 'jquery'
set autoindent
set smartindent
set cindent
inoremap { {<CR>}<up><end><CR>
