set nocompatible              " be iMproved, required
filetype off                  " required

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin('~/.vim/bundle')
Plugin 'airblade/vim-gitgutter'
Plugin 'gmarik/Vundle.vim', {'name': 'vundle.vim'}
Plugin 'tpope/vim-surround'
call vundle#end()
filetype plugin indent on

set number
syntax on

" Display the status line *always*
set laststatus=2

" Display the cursor line
set cursorline
hi CursorLine ctermbg=255 cterm=None gui=None
hi CursorLineNr ctermbg=255 cterm=None gui=None

" Display the color column
set colorcolumn=80

" Display a warning if &paste is set
set statusline+=%#error#
set statusline+=%{&paste?'[paste]':''}
set statusline+=%*

set statusline+=\ %t%m%r%h%w\ %=%({%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\&bomb)?\",B\":\"\")}%k\|%{&filetype}}%)\ %([%l,%v][%p%%]\ %)

set nofoldenable

" Set the colorscheme
colorscheme grb256

nnoremap ; :
nnoremap : ;

set autoindent
set smartindent
set cindent
